name: Android CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install Android SDK tools
      uses: android-actions/setup-android@v3

    - name: Install required NDK version
      run: sdkmanager "ndk;25.2.9519653"

    - name: Init Git Submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive

    - name: Prepare Dependencies
      run: ./gradlew androidDependencies

    - name: Build Release
      run: ./gradlew clean assembleRelease
      env:
        JVM_OPTS: -Xmx3200m

    - uses: actions/upload-artifact@v4
      with:
        name: pd-core-aar
        path: PdCore/build/outputs/aar

    - name: Publish to Sonatype
      if: github.event_name == 'push'
      run: ./gradlew publishToSonatype
      env:
        ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
        ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
        #ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
        #ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
